[tier1_ha_vms]
pihole-primary    ansible_host=10.0.30.10
pihole-secondary  ansible_host=10.0.30.11
authentik-primary ansible_host=10.0.30.30
authentik-replica ansible_host=10.0.30.31

[tier1_ha_vms:vars]
ansible_user=adm-deb
ansible_become=yes

[tier2_lxc]
arr-stack         ansible_host=10.0.30.50
media-streaming   ansible_host=10.0.30.55
personal-cloud    ansible_host=10.0.30.60
ingress           ansible_host=10.0.30.25
dev-tools         ansible_host=10.0.30.70

[tier2_lxc:vars]
ansible_user=root

[all:vars]
ansible_ssh_private_key_file=~/.ssh/id_ed25519